# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
