# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsapp', '0002_auto_20161219_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
