# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opsapp', '0003_auto_20161219_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlist',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverlist',
            name='uptime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
